name: JaCoCo Coverage Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Check Coverage with Maven
      # Lệnh verify sẽ chạy đủ compile -> test -> package -> check coverage
      run: mvn clean verify

    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v4
      if: always() # Luôn trích xuất báo cáo kể cả khi build lỗi
      with:
        name: jacoco-coverage-report
        path: target/site/jacoco/